### ISSUE TITLE
Does not work properly in dynamic forms  

### ISSUE THREAD

**Issue by M-Fares** [2amigos/yii2-date-picker-widget#11]
I don't know if should post this here or on dynamic form but I am posting anyway

I implemented it like this, the datepicker popup appears only for the first Item and not for the other dynamic items

<div class="panel panel-default">
        <div class="panel-heading"><h4><i class="glyphicon glyphicon-envelope"></i> خبرات العمل</h4></div>
        <div class="panel-body">
             <?php DynamicFormWidget::begin([
                'widgetContainer' => 'dynamicform_wrapper', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
                'widgetBody' => '.container-items', // required: css class selector
                'widgetItem' => '.item', // required: css class
                'limit' => 4, // the maximum times, an element can be cloned (default 999)
                'min' => 1, // 0 or 1 (default 1)
                'insertButton' => '.add-item', // css class
                'deleteButton' => '.remove-item', // css class
                'model' => $WorkExperiencesModels[0],
                'formId' => 'dynamic-form',
                'formFields' => [
                    'Title',
                    'Description',
                    'FKWorkSectorID',
                    'FKCountryID',
                    'FKCityID',
                    'StartDate',
                    'EndDate',
                ],
            ]); ?>

            <div class="container-items">
            <?php foreach ($WorkExperiencesModels as $i => $WorkExperiencesModel): ?>
                <div class="item panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title pull-left">خبرات العمل</h3>
                        <div class="pull-right">
                            <button type="button" class="add-item btn btn-success btn-xs"><i class="glyphicon glyphicon-plus"></i></button>
                            <button type="button" class="remove-item btn btn-danger btn-xs"><i class="glyphicon glyphicon-minus"></i></button>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-body">
                        <?php
                            // necessary for update action.
                            if (! $WorkExperiencesModel->isNewRecord) {
                                echo Html::activeHiddenInput($WorkExperiencesModel, "[{$i}]ID");
                            }
                        ?>
                        <?= $form->field($WorkExperiencesModel, "[{$i}]Title")->textInput(['maxlength' => true]) ?>
                        <div class="row">
                            <div class="col-sm-6">
                                <?= $form->field($WorkExperiencesModel, "[{$i}]Description")->textarea(['maxlength' => true]) ?>
                            </div>
                            <div class="col-sm-6">
                                <?= $form->field($WorkExperiencesModel, "[{$i}]FKWorkSectorID")->dropDownList(
                                ArrayHelper::map(Worksector::find()->all(), 'ID', 'Name'),           // Flat array ('id'=>'label')
                                ['prompt'=>'']    // options
                            ) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <?= $form->field($WorkExperiencesModel, "[{$i}]FKCountryID")->dropDownList(
                                    ArrayHelper::map(Countries::find()->all(), 'ID', 'Name'),           // Flat array ('id'=>'label')
                                    ['prompt'=>'select country',    // options
                                      'onchange'=>'
                                                    console.log("fired");
                                                    $.post("index.php?r=cities/list&id='.'"+$(this).val(),function(data){
                                                        $("[{$i}]select#workexperience-fkcityid").html(data);
                                                    });'
                                                 ])
                                ?>
                            </div>
                            <div class="col-sm-4">
                                <?= $form->field($WorkExperiencesModel, "[{$i}]FKCityID")->dropDownList(
                                    ArrayHelper::map(Cities::find()->all(), 'ID', 'Name'),           // Flat array ('id'=>'label')
                                    ['prompt'=>'']    // options
                                )
                                ?>
                            </div>
                            <div class="col-sm-4">
                             <?= $form->field($WorkExperiencesModel, "[{$i}]StartDate")->widget(
                                DatePicker::className(), [
                                    // inline too, not bad
                                     // 'inline' => true, 
                                     // modify template for custom rendering
                                    'template' => '{addon}{input}',
                                    'clientOptions' => [
                                        'autoclose' => true,
                                        'format' => 'yyyy-mm-dd',
                                        'startView'=>'year'
                                    ]
                            ]);?>

                            </div>
                            <div class="col-sm-4">
                             <?= $form->field($WorkExperiencesModel, "[{$i}]EndDate")->widget(
                                DatePicker::className(), [
                                    // inline too, not bad
                                     // 'inline' => true, 
                                     // modify template for custom rendering
                                    'template' => '{addon}{input}',
                                    'clientOptions' => [
                                        'autoclose' => true,
                                        'format' => 'yyyy-mm-dd',
                                        'startView'=>'year'
                                    ]
                            ]);?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
            </div>
            <?php DynamicFormWidget::end(); ?>
        </div>
    </div>

**Comment by tonydspaniard** [comment]
Mind checking the resulting javascript?

**Comment by Flashwade1990** [comment]
You should add datepicker manually for dynamically genereted instances:

function multipleDatepickers()
{
	$(".dynamicform_wrapper").on("afterInsert afterDelete", function(e, item) {
		var VarItemsQuantity = $('.item').length,
			VarCounter = 1;

		for(VarCounter; VarCounter < VarItemsQuantity; VarCounter++) {
			$('#WorkExperiencesModel-' + VarCounter + '-StartDate').
				parent().datepicker({"autoclose":true,	"format":"dd-M-yyyy", 'language':'ru',});
			$('#WorkExperiencesModel-' + VarCounter + '-EndDate').
				parent().datepicker({"autoclose":true,	"format":"dd-M-yyyy", 'language':'ru',});
		};
	});
}

**Comment by DanLivassan** [comment]
@Flashwade1990 Solution works fine!

**Comment by jhonnyfcr** [comment]
Donde agrego el codigo??
function multipleDatepickers()
{
    $(".dynamicform_wrapper").on("afterInsert afterDelete", function(e, item) {
        var VarItemsQuantity = $('.item').length,
            VarCounter = 1;
        for(VarCounter; VarCounter < VarItemsQuantity; VarCounter++) {
            $('#WorkExperiencesModel-' + VarCounter + '-StartDate').
                parent().datepicker({"autoclose":true,  "format":"dd-M-yyyy", 'language':'ru',});
            $('#WorkExperiencesModel-' + VarCounter + '-EndDate').
                parent().datepicker({"autoclose":true,  "format":"dd-M-yyyy", 'language':'ru',});
        };
    });
}

**Comment by tonydspaniard** [comment]
@jhonnyfcr use `$this->registerJs` and only: 

```js 
$(".dynamicform_wrapper").on("afterInsert afterDelete", function(e, item) {
        var VarItemsQuantity = $('.item').length,
            VarCounter = 1;
        for(VarCounter; VarCounter < VarItemsQuantity; VarCounter++) {
            $('#WorkExperiencesModel-' + VarCounter + '-StartDate').
                parent().datepicker({"autoclose":true,  "format":"dd-M-yyyy", 'language':'ru',});
            $('#WorkExperiencesModel-' + VarCounter + '-EndDate').
                parent().datepicker({"autoclose":true,  "format":"dd-M-yyyy", 'language':'ru',});
        };
    });
