### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by yogeshs1989** [2amigos/yii2-date-picker-widget#12]
I am trying to install this widget in mac machine. I went to my Yii2-advanced project folder in terminal and I ran this command

>composer require 2amigos/yii2-date-picker-widget:~1.0

After that it gives me this error:-

>Your requirements could not be resolved to an installable set of packages.

>  Problem 1
>    - 2amigos/yii2-date-picker-widget 1.0.5 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - 2amigos/yii2-date-picker-widget 1.0.4 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - 2amigos/yii2-date-picker-widget 1.0.3 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - 2amigos/yii2-date-picker-widget 1.0.2 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - 2amigos/yii2-date-picker-widget 1.0.1 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - 2amigos/yii2-date-picker-widget 1.0.0 requires bower-asset/bootstrap-datepicker 1.4.0 -> no matching package found.
>    - Installation request for 2amigos/yii2-date-picker-widget ~1.0 -> satisfiable by 2amigos/yii2-date-picker-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5].

Side Note:- I don't have bootstrap-datepicker in my composer.json file

**Comment by tonydspaniard** [comment]
@yogeshs1989 is on our composer: https://github.com/2amigos/yii2-date-picker-widget/blob/master/composer.json#L31 

Do you have the bower plugin installed for composer?

**Comment by yogeshs1989** [comment]
Yeah, it is installed, I forgot to mention the minimum stability is set to stable in my composer.

>"minimum-stability": "stable",

And because of that this error was occurring. After using below line the problem is resolved.

>"2amigos/yii2-date-picker-widget": "@dev"

**Comment by maulikpatelbtech** [comment]
I am getting below error while installing plugin using composer in yii2. Any help or suggestion.

> $ php composer.phar require 2amigos/yii2-gallery-widget:~1.0


./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-gallery-widget 1.0.3 requires bower-asset/blueimp-gallery ~2.17.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.2 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.1 requires bower-asset/blueimp-gallery ~2.15.0 -> no matching package found.
    - 2amigos/yii2-gallery-widget 1.0.0 requires bower-asset/blueimp-gallery ~2.15 -> no matching package found.
    - Installation request for 2amigos/yii2-gallery-widget ~1.0 -> satisfiable by 2amigos/yii2-gallery-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
