### ISSUE TITLE
Js and Css defined in the init function don't play well with yii asset command line

### ISSUE THREAD

**Issue by germanliu** [2amigos/yii2-date-picker-widget#17]
DatePickerAsset.php defines css and js properties in the init function. Is there any reason for this? 

When compressing and minifying those files with yii asset assets.php config/assets-prod.php (http://www.yiiframework.com/doc-2.0/guide-structure-assets.html) the widget still tries to publish them and gets an 404 error.

**Comment by tonydspaniard** [comment]
you are right @germanliu , do you have time for a PR? anybody?
