### ISSUE TITLE
input value doesnot change (no response) when click to select a date

### ISSUE THREAD

**Issue by zhanglianchengdotcom** [2amigos/yii2-date-picker-widget#20]
The datapicker widget shows up, but clicking got no response, the <intput> value does not change at all.

Besides, language not working.

```
    <?= $form->field($model, 'birth_date')->widget(
        DatePicker::className(), [
            // inline too, not bad
             'inline' => true,
            // 'language' => Yii::$app->language,
             // modify template for custom rendering
            'template' => '<div class="well well-sm" style="background-color: #fff; width:150px">{input}</div>',
            'clientOptions' => [
                'autoclose' => true,
                'format' => 'yyyy-MM-dd'
            ]
    ]);?>
```

**Comment by tonydspaniard** [comment]
@zhanglianchengdotcom the language needs to be set according to the locales that the jquery plugin has not `Yii::$app->language`. Please, check your browser for the error. 

Probably you have an error on your javascript thats why values are not changing. On another note, this is an inline calendar, `autoclose` won't work.

**Comment by zhanglianchengdotcom** [comment]
@tonydspaniard 
Thank you very much!
I don't know why it doen't work or why it works, but finally it works indeed. :smile:
