### ISSUE TITLE
I cant install this package it show error as

### ISSUE THREAD

**Issue by GowthamThangamani** [2amigos/yii2-date-picker-widget#21]
C:\wamp_new\www\yii2advance>php composer.phar require 2amigos/yii2-date-picker-w
idget:~1.0
You are running composer with xdebug enabled. This has a major impact on runtime
 performance. See https://getcomposer.org/xdebug
The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WIL
L* break in the future and it should be fixed ASAP (require ^1.0 for example).
./composer.json has been updated
The "yiisoft/yii2-composer" plugin requires composer-plugin-api 1.0.0, this *WIL
L* break in the future and it should be fixed ASAP (require ^1.0 for example).
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - 2amigos/yii2-date-picker-widget 1.0.x-dev requires bower-asset/bootstrap-d
atepicker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.5 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.4 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.3 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.2 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.1 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - 2amigos/yii2-date-picker-widget 1.0.0 requires bower-asset/bootstrap-datep
icker 1.4.0 -> no matching package found.
    - Installation request for 2amigos/yii2-date-picker-widget ~1.0 -> satisfiab
le by 2amigos/yii2-date-picker-widget[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5,
1.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more det
ails.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by bloftd** [comment]
i have the same problem

**Comment by bloftd** [comment]
its a problem on your composer run  

> composer global require "fxp/composer-asset-plugin:@dev"

then you be able to install this package

**Comment by iambillywilly** [comment]
When I trying install this package got an error. How to fix it?
```
[ErrorException]
Illegal offset type in isset or empty
```
P.S. before installing I run `composer global require "fxp/composer-asset-plugin:@dev"`
