### ISSUE TITLE
Uncaught TypeError: jQuery(...).parent(...).datepicker is not a function

### ISSUE THREAD

**Issue by whte** [2amigos/yii2-date-picker-widget#22]
Hi there,

Is there a way to identify which version of jquery are you using?

Or is there anyway that I could solve this issue?

I am using a templates which have the older version of jquery 

`'js/jquery-1.7.2.min.js',
        'js/excanvas.min.js',
        'js/chart.min.js',
        'js/bootstrap.js',
        'js/full-calendar/fullcalendar.min.js',
        'js/base.js',`

If I remove the jquery here, the error won't be showing and the datepicker will be working just fine.

However, I need those jquery in order to do other stuff so it can't be removed. 

Or maybe noConflict() can help?

**Comment by tonydspaniard** [comment]
Should be latest as the jquery version is registered by yii2
