### ISSUE TITLE
 autoclose not work

### ISSUE THREAD

**Issue by des1roer** [2amigos/yii2-date-picker-widget#23]
code

    $form->field($model, 'premiere')->widget(
            DatePicker::className(), [
        // inline too, not bad                
        'inline' => true,
        'language' => 'ru',
        // modify template for custom rendering
        'template' => '<div class="well well-sm" style="background-color: #fff; width:250px">{input}</div>',
        'clientOptions' => [
            'autoclose' => true,
            'format' => 'dd.mm.yyyy'
        ]
    ]);

result

http://i.imgur.com/TjGzDQ4.png
![screenshot_23](https://cloud.githubusercontent.com/assets/10970793/13946897/3a7b5142-f039-11e5-8a1d-7c87341e558d.png)

**Comment by tonydspaniard** [comment]
It works only if you don't set it as 'inline'

**Comment by des1roer** [comment]
without inline not work absolutely

**Comment by tonydspaniard** [comment]
Remove the 'template' too
