### ISSUE TITLE
Limit date Picker to  month and year, by discarding days. 

### ISSUE THREAD

**Issue by remyatgeorge** [2amigos/yii2-date-picker-widget#25]
Im using the date picker widget inside the gridview to filter. But i need a datepicker that shows only month and year.
I have tried many options like -
   'changeMonth'=>true,
   'changeYear'=>true,
   'changeDay'=>false,
 but not working.
This is my code:
```php 
  <?= GridView::widget([
                                'dataProvider' => $dataProvider,
                                'filterModel' => $searchModel,
                                'columns' => [
                                    'name',
                                    'otp_num',
                                    [
                                       'attribute'=> 'otp_created_date',
                                         'value'=>'otp_created_date',
                                         'format'=>'raw',
                                          'filter'=>DatePicker::widget([
                                                  'model' =>$searchModel,
                                                      'attribute' => 'otp_created_date',
                                                  'clientOptions' => [
                                                      'autoclose' => true,
                                                      'format' => 'yyyy-m-d',
                                                  ]
                                              ]),
                                     ],

                                ],
                                'options' => [
                                    'changeMonth'=>true,
                                    'changeYear'=>true,
                                    'changeDay'=>false,
                                ]
                            ]);
                            ?>

**Comment by dldamilola** [comment]
Try this [options](https://eternicode.github.io/bootstrap-datepicker/?markup=input&format=MM+yyyy&weekStart=&startDate=&endDate=&startView=1&minViewMode=1&maxViewMode=2&todayBtn=linked&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox)
This is bootstrap datepicker, not jQuery.

**Comment by elamparithi282** [comment]
echo DatePicker::widget([
        'name' => 'month_only', 
        'value' => date('M-Y', strtotime('+2 days')),
        'options' => ['placeholder' => 'Select issue date ...'],
        'pluginOptions' => [
                'autoclose' => true,
                'startView'=>'year',                                                                                                                  
                'minViewMode'=>'months',
                'format' => 'M-yyyy',
                'todayHighlight' => true
        ]
]);
