### ISSUE TITLE
Can't override javascript file in DatePickerAsset asset bundle

### ISSUE THREAD

**Issue by matjaz-elumina** [2amigos/yii2-date-picker-widget#26]
I see you've changed the way you include js files in the bundle. Now you set js in the init function which makes it impossible to override it in assetManager. Can you fix this? Thanks.

**Comment by tonydspaniard** [comment]
Do you have time for a PR?

**Comment by tonydspaniard** [comment]
same issue #17

**Comment by tonydspaniard** [comment]
Fixed on 806228c
