### ISSUE TITLE
Make property DateRangePicker::_template protected instead private

### ISSUE THREAD

**Issue by Mr-Maslo** [2amigos/yii2-date-picker-widget#32]
It's necessary because private property can not use in classes which extends DateRangePicker.
For example, it may come in handy to redefine template without redefining of method DateRangePicker::run().

**Comment by tonydspaniard** [comment]
Do you have time for a PR?

**Comment by Mr-Maslo** [comment]
**tonydspaniard**, what do you mean by "PR"?

**Comment by Mr-Maslo** [comment]
Done. [https://github.com/2amigos/yii2-date-picker-widget/pull/34](url)

**Comment by tonydspaniard** [comment]
Thanks!
