### ISSUE TITLE
Bootstrap-datepicker trigger 'show.bs.modal' when it is displayed

### ISSUE THREAD

**Issue by mrfinrod** [2amigos/yii2-date-picker-widget#37]
Described here https://github.com/eternicode/bootstrap-datepicker/issues/978

**Comment by tonydspaniard** [comment]
I'll review when i have time thanks. Nevertheless, PR are welcome.

**Comment by tonydspaniard** [comment]
@mrfinrod The solution is to use `stopPropagation` on your event callback.
