### ISSUE TITLE
The missing file: 'js/bootstrap-datepicker.js'.

### ISSUE THREAD

**Issue by pyboyxrb** [2amigos/yii2-date-picker-widget#40]
the missing file: 'js/bootstrap-datepicker.js'.  how to get it?

**Comment by tonydspaniard** [comment]
@pyboyxrb missing? should be automatically registered with the bundle? https://github.com/2amigos/yii2-date-picker-widget/blob/master/src/DatePickerAsset.php#L28

**Comment by ilyafreer** [comment]
how to disable the display of the time? The standard method fron bootstrap does not work.

I need to choose a user date only, without time

$form->field($model, 'datetime_birthday')->widget(DateTimePicker::className(), [
		'language' => 'ru',
		'pickButtonIcon' => 'glyphicon glyphicon-time',
		'clientOptions' => [
			'autoclose' => true,
			'format'=> "dd MM yyyy",
			'todayBtn' => true,
		]
	]);

**Comment by tonydspaniard** [comment]
Use DatePicker widget instead @ilyafreer
