### ISSUE TITLE
datepicker.css not found

### ISSUE THREAD

**Issue by sjnlabs2013** [2amigos/yii2-date-picker-widget#42]
![image](https://cloud.githubusercontent.com/assets/3591216/22282469/a0a56720-e302-11e6-9f79-9250f4053f80.png)

datepicker.css is not there assests ! 

![image](https://cloud.githubusercontent.com/assets/3591216/22282735/4a038b48-e304-11e6-8747-a35e53384612.png)

**Comment by tonydspaniard** [comment]
It is not on your `vendor/bower/bootstrap-datepicker/dist`? where is the bower folder setup?

**Comment by sjnlabs2013** [comment]
![image](https://cloud.githubusercontent.com/assets/3591216/23884456/bf33d2fc-0892-11e7-9903-c224cde6aad9.png)

A:\xampp_win32_5.6.12\htdocs\pm2\vendor\bower\bootstrap-datepicker\dist\css

**Comment by tonydspaniard** [comment]
@sjnlabs2013 thank you... we have changed: https://github.com/2amigos/yii2-date-picker-widget/blob/master/src/DatePickerAsset.php#L21 do you mind double checking again?

**Comment by tonydspaniard** [comment]
Have added new version tag. Simply do `composer update`. Hope it works.
