### ISSUE TITLE
Date 'format' is not respected on 'Update'.

### ISSUE THREAD

**Issue by Real-Gecko** [2amigos/yii2-date-picker-widget#44]
I use widget in my `_form.php` that is used both by `create` and `update` actions:
```php
        <?= $form->field($model, 'publication_date')->widget(
            DatePicker::className(), [
                'language' => 'ru',
                'clientOptions' => [
                    'autoclose' => true,
                    'format' => 'dd.mm.yyyy',
                    'todayBtn' => true,
                    'pickerPosition' => 'top-left'
                ]
        ]);?>
```
When I select desired date in `create` view, everything is fine:
![screenshot_20170420_175852](https://cloud.githubusercontent.com/assets/2231969/25229702/2096b500-25f3-11e7-8731-7fb0abdbe5a8.png)

But when I go to 'update' view I see that required field is rendered like this:
![screenshot_20170420_175241](https://cloud.githubusercontent.com/assets/2231969/25229488/4ece7e04-25f2-11e7-9ce0-9e0cb344ea62.png)
So, no `format` is respected during rendering the field.
Any ways to fix?

**Comment by tonydspaniard** [comment]
@Real-Gecko have you tried providing the same format on server and client? Otherwise, I highly recommend that you modify the value of the attribute prior placing it on the widget. Maybe on
