### ISSUE TITLE
0000-00-00 00:00:00 value on save

### ISSUE THREAD

**Issue by wibiesana** [2amigos/yii2-date-picker-widget#53]
Everytime i save i get value 0000-00-00 00:00:00 im using mariadb for the database

**Comment by TreeHouse98** [comment]
i have a seem problem

**Comment by TreeHouse98** [comment]
i solved the problem, it's in a input format data, you need set in 'clientOptions' => [
            'format' => 'yyyy-mm-dd'
        ];
At first i set a yyyy-M-dd, and M it's a name of the month, and when i was set mm it like '00' format

**Comment by wibiesana** [comment]
works for me
