### ISSUE TITLE
File datepicker.css is not found in 1.4.0

### ISSUE THREAD

**Issue by ElisDN** [2amigos/yii2-date-picker-widget#8]
Rename `datepicker.css` to `bootstrap-datepicker.css` for `bootstrap-datepicker:1.4.0`, please.

**Comment by tonydspaniard** [comment]
@ElisDN Thanks... forgot to even update for the Bootstrap 3 support too!

**Comment by ElisDN** [comment]
And 'js/locales/bootstrap-datepicker.' . $this->language . '**.min.**js'

**Comment by tonydspaniard** [comment]
@ElisDN seems i made a big mistake

**Comment by tonydspaniard** [comment]
@ElisDN mind testing the latest 1.0.2?
